# Generated by Django 2.2.5 on 2019-11-06 07:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_designation', models.CharField(max_length=150)),
                ('employee_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Employee_Department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mr', 'Mr.'), ('ms', 'Mrs.'), ('miss', 'Miss'), ('dr', 'Dr.')], default='Mr.', max_length=5)),
                ('full_name', models.CharField(max_length=15)),
                ('date_of_birth', models.DateTimeField()),
                ('phone_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', message='Phone Number must be of 12 Digits')])),
                ('aadhar_no', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[0-9]{12}$', message='Aadhar Number must be of 12 Digits')])),
                ('pan_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('type_of_joining', models.CharField(choices=[('part', 'Part Time'), ('full', 'Full Time'), ('part', 'Contracted')], default='Full Time', max_length=15)),
                ('tenth_subjects', models.CharField(max_length=20)),
                ('tenth_school', models.CharField(max_length=20)),
                ('tenth_board', models.CharField(max_length=20)),
                ('tenth_full_mark', models.IntegerField()),
                ('tenth_secured_mark', models.IntegerField()),
                ('tenth_percentage', models.FloatField()),
                ('twelth_stream', models.CharField(max_length=20)),
                ('twelth_college', models.CharField(max_length=20)),
                ('twelth_board', models.CharField(max_length=20)),
                ('twelth_full_mark', models.IntegerField()),
                ('twelth_secured_mark', models.IntegerField()),
                ('tewlth_percentage', models.FloatField()),
                ('degree_stream', models.CharField(max_length=20)),
                ('degree_college', models.CharField(max_length=20)),
                ('degree_university', models.CharField(max_length=20)),
                ('degree_full_mark', models.IntegerField(blank=True, null=True)),
                ('degree_secured_mark', models.IntegerField(blank=True, null=True)),
                ('degree_percentage', models.FloatField()),
                ('postdegree_stream', models.CharField(blank=True, max_length=20)),
                ('postdegree_college', models.CharField(blank=True, max_length=20)),
                ('postdegree_university', models.CharField(blank=True, max_length=20)),
                ('postdegree_full_mark', models.IntegerField(blank=True, null=True)),
                ('postdegree_secured_mark', models.IntegerField(blank=True, null=True)),
                ('postdegree_percentage', models.FloatField(blank=True, null=True)),
                ('employee_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Employee_Department')),
                ('employee_designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Employee_Designation')),
            ],
        ),
    ]
