# Generated by Django 2.2.5 on 2019-10-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('affiliation_body', models.CharField(max_length=100)),
                ('approval_body', models.CharField(max_length=100)),
                ('date_of_approval', models.DateField()),
                ('address', models.TextField()),
                ('corporate_address', models.TextField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(upload_to='')),
                ('attachment', models.FileField(upload_to='')),
                ('other_attachment', models.FileField(upload_to='')),
            ],
        ),
    ]
