# Generated by Django 2.2.5 on 2019-10-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type_of_institute',
            field=models.CharField(choices=[('school', 'school'), ('college', 'college')], default='school', max_length=100),
        ),
    ]
