# Generated by Django 2.2.5 on 2019-11-05 14:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0008_auto_20191105_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(choices=[('A+ve', 'A+ve'), ('A-ve', 'A-ve'), ('B+ve', 'B+ve'), ('B-ve', 'B-ve'), ('AB+ve', 'AB+ve'), ('AB-ve', 'AB-ve'), ('O+ve', 'O+ve'), ('O-ve', 'O-ve')], default='O+ve', max_length=5)),
                ('nationality', models.CharField(choices=[('india', 'India'), ('others', 'others')], default='india', max_length=10)),
                ('caste', models.CharField(choices=[('Gen', 'GEN'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('Others', 'Others')], default='Others', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', message='Phone Number must be of 10 Digits')])),
                ('aadhar_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[0-9]{12}$', message='Aadhar Number must be of 12 Digits')])),
                ('gender', models.CharField(max_length=10)),
                ('fathers_name', models.CharField(max_length=20)),
                ('fathers_occupation', models.CharField(max_length=30)),
                ('fathers_phone_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', message='Please Enter a Valid Phone Number')])),
                ('fathers_email_id', models.EmailField(max_length=254)),
                ('mothers_name', models.CharField(max_length=20)),
                ('mothers_occupation', models.CharField(max_length=30)),
                ('mothers_phone_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', message='Please Enter a Valid Phone Number')])),
                ('mothers_email_id', models.EmailField(blank=True, max_length=254)),
                ('tenth_board', models.CharField(blank=True, max_length=50, null=True)),
                ('tenth_subjects', models.CharField(blank=True, max_length=50, null=True)),
                ('tenth_school', models.CharField(blank=True, max_length=50, null=True)),
                ('tenth_full_mark', models.IntegerField(blank=True, null=True)),
                ('tenth_secured_mark', models.IntegerField(blank=True, null=True)),
                ('tenth_percentage', models.FloatField(blank=True, null=True)),
                ('twelth_board', models.CharField(max_length=20)),
                ('twelth_stream', models.CharField(max_length=20)),
                ('twelth_school', models.CharField(max_length=20)),
                ('twelth_full_mark', models.IntegerField(blank=True, null=True)),
                ('twelth_secured_mark', models.IntegerField(blank=True, null=True)),
                ('tewlth_percentage', models.FloatField(blank=True, null=True)),
                ('degree_stream', models.CharField(blank=True, max_length=20, null=True)),
                ('degree_college', models.CharField(blank=True, max_length=20, null=True)),
                ('degree_university', models.CharField(blank=True, max_length=20, null=True)),
                ('degree_full_mark', models.IntegerField(blank=True, null=True)),
                ('degree_secured_mark', models.IntegerField(blank=True, null=True)),
                ('degree_percentage', models.FloatField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Course')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Stream')),
                ('year_sem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Year_Sem')),
            ],
        ),
    ]
