# Generated by Django 2.2.5 on 2019-11-07 06:37

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=student.models.PathAndRename('documents/2019/11/07')),
        ),
    ]
