# Generated by Django 2.2.5 on 2019-11-11 06:36

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20191109_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=student.models.PathAndRename('documents/2019/11/11')),
        ),
    ]
