# Generated by Django 2.2.5 on 2019-11-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20191112_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enr_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
