# Generated by Django 2.2.5 on 2019-11-13 06:53

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_enr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=student.models.PathAndRename('documents/2019/11/13')),
        ),
    ]
